### ISSUE TITLE
[feature request] use scrapy instead of browser

### ISSUE THREAD

**Issue by skochinsky** [Rexzarrax/Biosup#1]
[scrapy](https://scrapy.org/) is **the** framework specifically for scraping web pages. It should not be necessary to run a full browser just to download some HTML. Here is a previous tool using it, unfortunately it got stale as websites changed but it should be a good starting point:
https://github.com/theopolis/uefi-spider

**Comment by Rexzarrax** [comment]
Hi mate,

I will look into this method when i get a chance, my main issue was sites that use JavaScript to load aspects of the site i needed (the download links if i remember correctly)

**Comment by Rexzarrax** [comment]
Thinking about this a bit further and considering what i plan to do the project going forward i dont beleive this will be a high priority. 

My Plan is to move most of the gathering of required URL's and data to the cloud so its a easier hit for each individual run. 

I will look more into this as a backup option to if the server is down when biosup is run. 
I jjust need to finish uni first then ill have more time to work on this project.
